# config file for vision transformer

model:
  name: 'VisionTransformer'
  load_weights: False
  image_size: 360
  patch_size: 36
  num_layers: 12
  num_heads: 16
  hidden_dim: 128
  mlp_dim: 512
  num_classes: 2048  # Assuming 180*360

data:
  file_path: './sst_weekly.mat'

training:
  num_epochs: 3
  fig_num: 1914
  batch_size: 32
  learning_rate: 0.0001
  start_point: 0
  sensor_num: [10]
  sensor_seed: [4]
  sigma: 0.05
  input_type: "VIT"

testing:
  fig_num: 256
  batch_size: 32
  start_point: 25
  norm: "L2"
  sensor_num: [20]
  sensor_seed: [553]
  sigma: 0.05
  input_type: "VIT"

device:
  prefer_gpu: true

output:
  model_result: 'sst_vit_result_2'
  model_save_path: 'model/sst_vit_test_2.pth'
