# config file for vcnn

model:
  name: 'CNN'
  load_weights: False
  channels: 48
  kernel_size: 7
  padding: 3

data:
  file_path: './sst_weekly.mat'

training:
  num_epochs: 3
  fig_num: 1914
  batch_size: 32
  learning_rate: 0.01
  start_point: 0
  sensor_num: [100]
  sensor_seed: [4]
  sigma: 0.15
  input_type: "CNN"

testing:
  fig_num: 256
  batch_size: 32
  start_point: 1656
  norm: "L2"
  sensor_num: [10,20]
  sensor_seed: [4,9]
  sigma: 0.0
  input_type: "CNN"

device:
  prefer_gpu: true

output:
  model_result: 'sst_cnn_result_1'
  model_save_path: 'model/sst_cnn_test_2.pth'
