# config file for resnet

model:
  name: 'ResNet'
  load_weights: False
  size: 18

data:
  file_path: './sst_weekly.mat'

training:
  num_epochs: 5
  fig_num: 1914
  batch_size: 32
  learning_rate: 0.01
  start_point: 0
  sensor_num: [100]
  sensor_seed: [4]
  sigma: 0.0
  input_type: "RES"

testing:
  fig_num: 256
  batch_size: 32
  start_point: 0
  norm: "L2"
  sensor_num: [100]
  sensor_seed: [4]
  sigma: 0.0
  input_type: "RES"

device:
  prefer_gpu: true

output:
  model_result: 'sst_res_result_1'
  model_save_path: 'model/sst_res_test.pth'
